name: Netlify Preview
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.10.1'
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes")' -e 'remotes::install_github("rstudio/distill")'
      - name: Build
        run: |
          rm -rf docs/
          R -e 'for (post in dir("_posts/", pattern = "*.Rmd", recursive = TRUE)) rmarkdown::render(paste0("_posts/", post))'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './docs'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 3
